# Generated by Django 3.2.6 on 2021-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(max_length=50, verbose_name='Symbol')),
                ('price', models.FloatField(verbose_name='Price')),
                ('change_30d', models.FloatField(null=True, verbose_name='Change 30d')),
                ('change_60d', models.FloatField(null=True, verbose_name='Change 60d')),
                ('change_90d', models.FloatField(null=True, verbose_name='Change 90d')),
                ('max_supply', models.FloatField(null=True, verbose_name='Max supply')),
                ('circulating_supply', models.FloatField(verbose_name='Circulating supply')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('avg_value', models.FloatField(null=True, verbose_name='Average value')),
            ],
            options={
                'verbose_name': 'currency average',
                'verbose_name_plural': 'currencies averages',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cryptocurrency name')),
                ('created', models.DateTimeField(verbose_name='Created')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Closed')], default=1)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'currency data',
                'verbose_name_plural': 'currencies data',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('id',),
            },
        ),
    ]
